kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.27.3
- role: worker
  image: kindest/node:v1.27.3
  labels:
    datacenter: mg # Наш "Мегацод"
    segment: sandbox
- role: worker
  image: kindest/node:v1.27.3
  labels:
    datacenter: gm # Наш "Гигацод"
    segment: sandbox